version: "3.9"
networks:
  deploy-guide-dev:
    default: 
      driver: bridge
services:
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: deploy-guide
    ports:
      - 5431:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5051:5050
    depends_on:
      - postgres_db
volumes:
  postgres-data: